version: '3.8'

services:
  web:
    build: ./web-service
    container_name: 2022BCD0053-web
    ports:
      - "8080:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydb

  worker:
    build: ./worker-service
    container_name: 2022BCD0053-worker
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: 2022BCD0053-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
